### ISSUE TITLE
RCS1036 should allow empty line before "} while (..);"

### ISSUE THREAD

**Issue by magicware** [JosefPihrt/RoslynTools#10]
RCS1036 should allow (or require!) empty line before "} while (..);"

Because this:

![image](https://cloud.githubusercontent.com/assets/8859303/17552910/2b42d3e2-5f03-11e6-8017-b387c6e21b11.png)

In my opinion looks better than this:

![image](https://cloud.githubusercontent.com/assets/8859303/17552899/19962bb2-5f03-11e6-9f5a-f6632790fd47.png)

**Comment by JosefPihrt** [comment]
cf75042d27c8a15a18a36d0ff7194b448a52e1af
