### ISSUE TITLE
Please add refactoring 'introduce and initialize local variable'

### ISSUE THREAD

**Issue by mwijnands** [JosefPihrt/RoslynTools#11]
An example can be found here: https://github.com/hakenr/RoslynCodeRefactoringPlayground

What it does is this: http://trydis.github.io/assets/roslyn-refactoring-new-popup.PNG

Something we all do a million times :smiley:

**Comment by JosefPihrt** [comment]
Fixed with 2b93bf46e955073559a2f6e6fbc1f8da15fbbfe7

**Comment by mwijnands** [comment]
Wow, great work, thanks! Can't wait for the next release of the VS extensions!

**Comment by JosefPihrt** [comment]
It's been released.

Feel free to review my extension on Visual Studio Gallery :)
