### ISSUE TITLE
Please add refactoring to join lines

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/RoslynTools#15]
There's a piece of code like this:
````C#
byte[] destinationBuffer = CopyImage (
			sourceBuffer,
			sourceData.Width,
			sourceData.Height,
			sourceData.Stride,
			destinationData.Stride);
````

Please add a refactoring to join a separated statement into a single line.

**Comment by JosefPihrt** [comment]
That refactoring already exists, its title is "Format all arguments on a single line".

It works both ways with "Format each argument on a separate line".

**Comment by wmjordan** [comment]
Oops.
I selected those lines and expected that the refactoring would show up, but it did not.
After your mentioning the existence, I placed the caret inside the statement without selecting a single character. The refactoring could show up after that.

**Comment by JosefPihrt** [comment]
This behaviour is intentional, because is there is selected text, it is likely that you want to use some built-in refactoring (ExtractMethod, IntroduceVariable) and refactorings mentioned above would only bother you, because they are displayed above built-in refactorings.
