### ISSUE TITLE
Reusing WhiteSpaceOrEndOfLineRemover

### ISSUE THREAD

**Issue by pgenfer** [JosefPihrt/RoslynTools#8]
Hi Josef,
sorry to contact you this way but I wasn't able to find your contact information on github. 

I am currently working on an [open source extension](https://github.com/pgenfer/mixinSharp)  for Visual Studio and had to remove unnecessary white spaces when generating property accessor methods.   

I recognized that your [WhiteSpaceOrEndOfLineRemover] (https://github.com/JosefPihrt/RoslynTools/blob/master/source/Common/CSharp/Removers/WhitespaceOrEndOfLineRemover.cs) does exactly what I was looking for so I took parts of your implementatio for my  extension (see my implementation [here](https://github.com/pgenfer/mixinSharp/blob/master/MixinRefactoring/SyntaxWriter/RemoveWhitespaceWriter.cs)).  

I referenced your work and your license information in my code, but please let me know if it's ok for you that I am resuing your code this way or if I should add any further information. 

Thank you in advance,

Best regards,

Patric

P.S.: By the way, your RoslynTools are really great work!

**Comment by JosefPihrt** [comment]
Hi, I'm pleased that you like my project. It is open source, so you can use it according to licence.
