### ISSUE TITLE
Please add refactoring to add braces

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/RoslynTools#9]
Please support adding the braces for single line `if` and `for` statements.

Before:
````C#
if (i < 0)
    i = 0;

for (int i = 0; i < 3; i++)
     x += i;
````

After:
````C#
if (i < 0) {
    i = 0;
}

for (int i = 0; i < 3; i++) {
     x += i;
}
````

**Comment by JosefPihrt** [comment]
This feature already exists, it's called "Replace embedded statement with block"

**Comment by wmjordan** [comment]
Thanks for the reply.
I placed the caret into the `if` statement, but no light bulb appeared on the left side of the editor.
I found that the code fix only appeared when I press Ctrl+. to manually trigger the refactoring.
However, in some situations, the light bulb could appeared automatically.

BTW, is it possible to provide the code-fix at document or project level?

**Comment by JosefPihrt** [comment]
1. Refactoring "Replace embedded statement with block" is available only when caret is on embedded statement.

2. Bulb appears only if there is a code fix available. Code fix represent a fix for a diagnostic reported by an analyzer. Refactorings are calculated "on demand" (when you pres ctrl+.) so there is no light bulb for refactorings.

3. If you want to have braces everywhere, you can use analyzer "RCS1007 - Avoid embedded statement". This analyzer is not enabled by default so you have to turn it on.

**Comment by wmjordan** [comment]
Understood.
Thanks for the reply.
Currently I am using the Refactor component only. I might try the Analyzer component later :)
